server:
  port: 8081

spring:
  application:
    name: VisionWear-User
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB
  datasource:
    driver-class-name: ${vision.datasource.driver-class-name}
    url: ${vision.datasource.user.url}
    username: ${vision.datasource.user.username}
    password: ${vision.datasource.user.password}
  cloud:
      nacos:
        server-addr: ${nacos.server-addr}

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath*:/mapper/**/*.xml

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

knife4j:
  enable: true
  production: false

logging:
  level:
    com:
      wtu:
        mapper: debug
        service: info
        controller: info

vision:
  jwt:
    secretKey: ${vision.jwt.secret-key}
    ttl: ${vision.jwt.ttl}
    tokenName: ${vision.jwt.token-name}
  api:
    key: ${vision.api.secret-key}
    url: ${vision.api.url}
    timeout: ${vision.api.timeout}
  maxSize: 10485760

wtu:
  alioss:
    endpoint: ${vision.alioss.endpoint}
    access-key-id: ${vision.alioss.access-key-id}
    access-key-secret: ${vision.alioss.access-key-secret}
    bucket-name: ${vision.alioss.bucket-name}