server:
  port: 8082  # 图片服务端口

spring:
  application:
    name: VisionWear-Image
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB

  datasource:
    driver-class-name: ${vision.datasource.driver-class-name}
    url: ${vision.datasource.image.url}
    username: ${vision.datasource.image.username}
    password: ${vision.datasource.image.password}

  cloud:
    openfeign:
      okhttp:
        enabled: true


logging:
  level:
    com:
      wtu:
        mapper: debug
        service: info
        controller: info

