server:
  port: 8082  # 图片服务端口

spring:
  application:
    name: VisionWear-Image
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB

  datasource:
    driver-class-name: ${vision.datasource.driver-class-name}
    url: ${vision.datasource.user.url}
    username: ${vision.datasource.user.username}
    password: ${vision.datasource.user.password}
  cloud:
    nacos:
        server-addr: 8.155.5.178:8848

logging:
  level:
    com:
      wtu:
        mapper: debug
        service: info
        controller: info 