server:
  port: 8080  # 网关端口

spring:
  application:
    name: VisionWear-GateWay
  cloud:
    nacos:
      server-addr: 8.155.5.178:8848
    gateway:
      routes:
        - id: user-service
          uri: lb://VisionWear-User
          predicates:
            - Path=/api/user/**,/api/auth/**
        - id: image-service
          uri: lb://VisionWear-Image
          predicates:
            - Path=/api/image/**
        - id: community-service
          uri: lb://VisionWear-Community
          predicates:
            - Path=/api/community/**

  profiles:
    active: dev


logging:
  level:
    org.springframework.cloud.gateway: debug

# knife4j 网关聚合
knife4j:
  gateway:
    enabled: true
    # 指定服务发现的模式聚合微服务文档，并且是默认 default 分组
    strategy: discover
    discover:
      # OpenAPI 3.0 规范
      version: openapi3
      enabled: true
vision:
  jwt:
    secretKey: ${vision.jwt.secret-key}
    ttl: ${vision.jwt.ttl}
    refreshTtl: ${vision.jwt.refresh-ttl}
    accessTokenName: ${vision.jwt.access-token-name}
    refreshTokenName: ${vision.jwt.refresh-token-name}